kind: pipeline
name: oati_sam_build

steps:
  - name: install sam-cli
    image: amazonlinux:2
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo "Installing SAM CLI"
      - yum update -y
      - yum install -y unzip curl
      - curl -L "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip" -o "aws-sam-cli-linux-x86_64.zip"
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - ./sam-installation/install
      - sam --version
      - ls -la src/handlers/gofpdf_syllabus
      - sam build --use-container

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
