kind: pipeline
name: oati_sam_build

steps:
- steps:
  name: sam_build
  image: plugins/aws-sam-build
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  settings:
    template_file_path: template.yaml
    build_command_options: "--debug"
    build_image: public.ecr.aws/sam/build-python3.9:1.112.0-20240313001230
  when:
  branch:
    - master
  event:
    - push

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
