kind: pipeline
name: oati_sam_build

steps:
  - name: sam_build
    image: amazon/aws-sam-cli-emulation-image-python3.9
    commands:
      - echo "Building SAM Application"
      - sam build
    when:
    branch:
      - master
    event:
      - push
