AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  prueba-piloto-lambda-crud

  SAM Template for prueba-piloto-lambda-crud

Globals:
  Function:
    Timeout: 60

Parameters:
  CrudUsername:
    Description: Database User Username
    Type: String
    Default: ""
  CrudPass:
    Type: String
    Default: ""
  CrudHost:
    Type: String
    Default: ""
  CrudPort:
    Type: String
    Default: ""
  CrudDB:
    Type: String
    Default: "prueba_piloto_lambda_db"
  Timezone:
    Type: String
    Default: "America/Bogota"

Resources:
  CrudSyllabusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/crud_syllabus/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SYLLABUS_CRUD_HOST: !Ref CrudHost
          SYLLABUS_CRUD_PORT: !Ref CrudPort
          SYLLABUS_CRUD_USERNAME: !Ref CrudUsername
          SYLLABUS_CRUD_PASS: !Ref CrudPass
          SYLLABUS_CRUD_DB: !Ref CrudDB
          TIMEZONE: !Ref Timezone
      Events:
        CreateSyllabus:
          Type: Api
          Properties:
            Path: /syllabus
            Method: post

        GetSyllabus:
          Type: Api
          Properties:
            Path: /syllabus/{id}
            Method: get

        GetAllSyllabus:
          Type: Api
          Properties:
            Path: /syllabus
            Method: get

        PutSyllabus:
          Type: Api
          Properties:
            Path: /syllabus/{id}
            Method: put

        DeleteSyllabus:
          Type: Api
          Properties:
            Path: /syllabus/{id}
            Method: delete

  PostSyllabusGofpdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/gofpdf_syllabus/
      Handler: gofpdf_syllabus
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        GetSyllabusGofPdf:
          Type: Api
          Properties:
            Path: /v2/syllabus/template
            Method: post

  PostSyllabusXLSXFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/spreadsheet_syllabus/
      Handler: spreadsheet_syllabus
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        GetSyllabusXLSX:
          Type: Api
          Properties:
            Path: /syllabus/template/spreadsheet
            Method: post

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/health/
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 10
      Events:
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: get

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"