AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  prueba-piloto-lambda-crud

  SAM Template for prueba-piloto-lambda-crud

Globals:
  Function:
    Timeout: 60

Parameters:
  CrudUsername:
    Description: Database User Username
    Type: String
    Default: ""
  CrudPass:
    Type: String
    Default: ""
  CrudHost:
    Type: String
    Default: ""
  CrudPort:
    Type: String
    Default: ""
  CrudDB:
    Type: String
    Default: "prueba_piloto_lambda_db"
  Timezone:
    Type: String
    Default: "America/Bogota"

Resources:
  CreateSyllabusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/create_syllabus/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SYLLABUS_CRUD_HOST: !Ref CrudHost
          SYLLABUS_CRUD_PORT: !Ref CrudPort
          SYLLABUS_CRUD_USERNAME: !Ref CrudUsername
          SYLLABUS_CRUD_PASS: !Ref CrudPass
          SYLLABUS_CRUD_DB: !Ref CrudDB
          TIMEZONE: !Ref Timezone
      Events:
        CreateSyllabus:
          Type: Api
          Properties:
            Path: /syllabus
            Method: post

  GetSyllabusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/get_syllabus/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SYLLABUS_CRUD_HOST: !Ref CrudHost
          SYLLABUS_CRUD_PORT: !Ref CrudPort
          SYLLABUS_CRUD_USERNAME: !Ref CrudUsername
          SYLLABUS_CRUD_PASS: !Ref CrudPass
          SYLLABUS_CRUD_DB: !Ref CrudDB
      Events:
        GetSyllabus:
          Type: Api
          Properties:
            Path: /syllabus/{id}
            Method: get

  GetAllSyllabusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/get_all_syllabus/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SYLLABUS_CRUD_HOST: !Ref CrudHost
          SYLLABUS_CRUD_PORT: !Ref CrudPort
          SYLLABUS_CRUD_USERNAME: !Ref CrudUsername
          SYLLABUS_CRUD_PASS: !Ref CrudPass
          SYLLABUS_CRUD_DB: !Ref CrudDB
      Events:
        GetSyllabus:
          Type: Api
          Properties:
            Path: /syllabus
            Method: get

  PutSyllabusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/put_syllabus/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SYLLABUS_CRUD_HOST: !Ref CrudHost
          SYLLABUS_CRUD_PORT: !Ref CrudPort
          SYLLABUS_CRUD_USERNAME: !Ref CrudUsername
          SYLLABUS_CRUD_PASS: !Ref CrudPass
          SYLLABUS_CRUD_DB: !Ref CrudDB
          TIMEZONE: !Ref Timezone
      Events:
        PutSyllabus:
          Type: Api
          Properties:
            Path: /syllabus/{id}
            Method: put

  DeleteSyllabusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/delete_syllabus/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SYLLABUS_CRUD_HOST: !Ref CrudHost
          SYLLABUS_CRUD_PORT: !Ref CrudPort
          SYLLABUS_CRUD_USERNAME: !Ref CrudUsername
          SYLLABUS_CRUD_PASS: !Ref CrudPass
          SYLLABUS_CRUD_DB: !Ref CrudDB
          TIMEZONE: !Ref Timezone
      Events:
        DeleteSyllabus:
          Type: Api
          Properties:
            Path: /syllabus/{id}
            Method: delete

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/health/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: get

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"